### PR TITLE
Homework_8_Dergunov_Nikita

### PR DESCRIPTION
**Pull request by nikita17th**
# JMH version: 1.25
# VM version: JDK 11.0.12, Java HotSpot(TM) 64-Bit Server VM, 11.0.12+8-LTS-237
# VM invoker: C:\Program Files\Java\jdk-11.0.12\bin\java.exe
# VM options: -Xms1G -Xmx1G
# Warmup: 2 iterations, 10 s each
# Measurement: 3 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: ru.mail.polis.ads.hash.HashTableJmh.benchmarkDefaultHashmap
# Parameters: (TEST_DATA_SIZE = 1000000)

# Run progress: 0,00% complete, ETA 00:05:00
# Warmup Fork: 1 of 1
# Warmup Iteration   1: 365,008 ms/op
# Warmup Iteration   2: 360,886 ms/op
Iteration   1: 374,146 ms/op
Iteration   2: 376,832 ms/op
Iteration   3: 382,653 ms/op

# Run progress: 16,67% complete, ETA 00:07:34
# Fork: 1 of 2
# Warmup Iteration   1: 364,294 ms/op
# Warmup Iteration   2: 382,871 ms/op
Iteration   1: 371,942 ms/op
Iteration   2: 379,064 ms/op
Iteration   3: 377,348 ms/op

# Run progress: 33,33% complete, ETA 00:06:09
# Fork: 2 of 2
# Warmup Iteration   1: 347,624 ms/op
# Warmup Iteration   2: 366,892 ms/op
Iteration   1: 356,395 ms/op
Iteration   2: 353,451 ms/op
Iteration   3: 373,279 ms/op

Result "ru.mail.polis.ads.hash.HashTableJmh.benchmarkDefaultHashmap":
  368,580 �(99.9%) 30,655 ms/op [Average]
  (min, avg, max) = (353,451, 368,580, 379,064), stdev = 10,932
  CI (99.9%): [337,925, 399,235] (assumes normal distribution)

# JMH version: 1.25
# VM version: JDK 11.0.12, Java HotSpot(TM) 64-Bit Server VM, 11.0.12+8-LTS-237
# VM invoker: C:\Program Files\Java\jdk-11.0.12\bin\java.exe
# VM options: -Xms1G -Xmx1G
# Warmup: 2 iterations, 10 s each
# Measurement: 3 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: ru.mail.polis.ads.hash.HashTableJmh.benchmarkHashTableImpl
# Parameters: (TEST_DATA_SIZE = 1000000)

# Run progress: 50,00% complete, ETA 00:04:39
# Warmup Fork: 1 of 1
# Warmup Iteration   1: 1344,971 ms/op
# Warmup Iteration   2: 1416,924 ms/op
Iteration   1: 1432,787 ms/op
Iteration   2: 1351,729 ms/op
Iteration   3: 1331,942 ms/op

# Run progress: 66,67% complete, ETA 00:03:08
# Fork: 1 of 2
# Warmup Iteration   1: 1456,441 ms/op
# Warmup Iteration   2: 1520,627 ms/op
Iteration   1: 1432,678 ms/op
Iteration   2: 1389,593 ms/op
Iteration   3: 1460,623 ms/op

# Run progress: 83,33% complete, ETA 00:01:34
# Fork: 2 of 2
# Warmup Iteration   1: 1514,045 ms/op
# Warmup Iteration   2: 1357,152 ms/op
Iteration   1: 1401,304 ms/op
Iteration   2: 1446,624 ms/op
Iteration   3: 1360,209 ms/op

Result "ru.mail.polis.ads.hash.HashTableJmh.benchmarkHashTableImpl":
  1415,172 �(99.9%) 106,626 ms/op [Average]
  (min, avg, max) = (1360,209, 1415,172, 1460,623), stdev = 38,024
  CI (99.9%): [1308,546, 1521,797] (assumes normal distribution)

# Run complete. Total time: 00:09:25

REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
experiments, perform baseline and negative tests that provide experimental control, make sure
the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
Do not assume the numbers tell you what you want them to tell.

Benchmark                             (TEST_DATA_SIZE)  Mode  Cnt     Score     Error  Units
HashTableJmh.benchmarkDefaultHashmap           1000000  avgt    6   368,580 �  30,655  ms/op
HashTableJmh.benchmarkHashTableImpl            1000000  avgt    6  1415,172 � 106,626  ms/op

Benchmark result is saved to C:\Users\nikit\Desktop\Technopolis\Algorithm\2021-ads\build\results\jmh\results.txt

### CODE REVIEW

**Comment by legohedgehog** [comment]
зачтено на 9

**Comment by legohedgehog** [comment]
можно исправить в течении суток, если не хочется, можно закрыть ПР

**Comment by nikita17th** [comment]
Я бы исправил, а что именно не подскажите?)

**Review by legohedgehog — COMMENTED** [review]
можно исправить комментарии с "-1" в течении суток, если не хочется, можно закрыть ПР

**Comment by legohedgehog** [comment]
зачтено

**Pull request closed without merging**
