### PR TITLE
Homework_8_Shevtsov_Artem

### PR DESCRIPTION
**Pull request by PrimeFall**

### CODE REVIEW

**Comment by PrimeFall** [comment]
# JMH version: 1.25
# VM version: JDK 17, Java HotSpot(TM) 64-Bit Server VM, 17+35-LTS-2724
# VM invoker: D:\JavaDK\JavaDK17\bin\java.exe
# VM options: -Xms1G -Xmx1G
# Warmup: 2 iterations, 10 s each
# Measurement: 3 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: ru.mail.polis.ads.hash.HashTableJmh.benchmarkDefaultHashmap
# Parameters: (TEST_DATA_SIZE = 1000000)

# Run progress: 0,00% complete, ETA 00:05:00
# Warmup Fork: 1 of 1
# Warmup Iteration   1: 267,332 ms/op
# Warmup Iteration   2: 237,103 ms/op
Iteration   1: 252,226 ms/op
Iteration   2: 215,256 ms/op
Iteration   3: 221,244 ms/op

# Run progress: 16,67% complete, ETA 00:06:14
# Fork: 1 of 2
# Warmup Iteration   1: 218,602 ms/op
# Warmup Iteration   2: 212,664 ms/op
Iteration   1: 210,576 ms/op
Iteration   2: 209,698 ms/op
Iteration   3: 209,744 ms/op

# Run progress: 33,33% complete, ETA 00:04:58
# Fork: 2 of 2
# Warmup Iteration   1: 222,534 ms/op
# Warmup Iteration   2: 213,257 ms/op
Iteration   1: 218,318 ms/op
Iteration   2: 215,729 ms/op
Iteration   3: 210,865 ms/op


Result "ru.mail.polis.ads.hash.HashTableJmh.benchmarkDefaultHashmap":
  212,488 �(99.9%) 10,195 ms/op [Average]
  (min, avg, max) = (209,698, 212,488, 218,318), stdev = 3,636
  CI (99.9%): [202,293, 222,684] (assumes normal distribution)


# JMH version: 1.25
# VM version: JDK 17, Java HotSpot(TM) 64-Bit Server VM, 17+35-LTS-2724
# VM invoker: D:\JavaDK\JavaDK17\bin\java.exe
# VM options: -Xms1G -Xmx1G
# Warmup: 2 iterations, 10 s each
# Measurement: 3 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op
# Benchmark: ru.mail.polis.ads.hash.HashTableJmh.benchmarkHashTableImpl
# Parameters: (TEST_DATA_SIZE = 1000000)

# Run progress: 50,00% complete, ETA 00:03:42
# Warmup Fork: 1 of 1
# Warmup Iteration   1: 676,782 ms/op
# Warmup Iteration   2: 665,549 ms/op
Iteration   1: 657,273 ms/op
Iteration   2: 654,728 ms/op
Iteration   3: 679,394 ms/op

# Run progress: 66,67% complete, ETA 00:02:29
# Fork: 1 of 2
# Warmup Iteration   1: 680,212 ms/op
# Warmup Iteration   2: 664,125 ms/op
Iteration   1: 660,176 ms/op
Iteration   2: 665,286 ms/op
Iteration   3: 664,056 ms/op

# Run progress: 83,33% complete, ETA 00:01:15
# Fork: 2 of 2
# Warmup Iteration   1: 678,791 ms/op
# Warmup Iteration   2: 656,235 ms/op
Iteration   1: 656,374 ms/op
Iteration   2: 658,388 ms/op
Iteration   3: 664,426 ms/op


Result "ru.mail.polis.ads.hash.HashTableJmh.benchmarkHashTableImpl":
  661,451 �(99.9%) 10,275 ms/op [Average]
  (min, avg, max) = (656,374, 661,451, 665,286), stdev = 3,664
  CI (99.9%): [651,176, 671,726] (assumes normal distribution)


# Run complete. Total time: 00:07:31

REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
experiments, perform baseline and negative tests that provide experimental control, make sure
the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
Do not assume the numbers tell you what you want them to tell.

Benchmark                             (TEST_DATA_SIZE)  Mode  Cnt    Score    Error  Units
HashTableJmh.benchmarkDefaultHashmap           1000000  avgt    6  212,488 � 10,195  ms/op
HashTableJmh.benchmarkHashTableImpl            1000000  avgt    6  661,451 � 10,275  ms/op

Benchmark result is saved to D:\technopolis\algorithms\2021-ads\build\results\jmh\results.txt

**Comment by legohedgehog** [comment]
зачтено на 8

**Comment by legohedgehog** [comment]
можно исправить в течении суток, если не хочется, можно закрыть ПР

**Review by legohedgehog — COMMENTED** [review]
можно исправить комментарии с "-1" в течении суток, если не хочется, можно закрыть ПР

**Comment by legohedgehog** [comment]
исправлений не увидел, закрываю как есть

**Pull request closed without merging**
